American industry rework #2
Cold-War-Project/CWP-Main pull request #190
Opened 2023-04-14 03:40 UTC by Mercur-3

please work please work please work please work

2023-04-14 14:48 UTC, JackEPepper requested changes
Seems to start with a shortage of professional services, but activating professional services PM leads to a shortage of glass due to activating industrial cities.

2023-04-16 04:59 UTC, Mercur-3 commented
> 

I fixed it

2023-04-16 22:00 UTC, JackEPepper approved these changes

2023-04-17 00:33 UTC, DZappala approved these changes

2023-04-17 00:33 UTC, merged