Ai improvement (dynamic budget) + fix + comments
Cold-War-Project/CWP-Main pull request #255
Opened 2023-04-24 21:53 UTC by ademblon

- Make the ai make dynamic budget between construction and military. There's a lot to say, too much for a PR, but it lays the groundwork for a better and maintainable aroai.
- Fix ports construction (again)
- a few comments here and there

2023-04-24 22:44 UTC, JackEPepper requested changes

2023-04-24 22:44 UTC, JackEPepper commented on common/production_methods/01_industry.txt
The negative pollution generation seems to have gotten deleted

2023-04-24 22:44 UTC, JackEPepper commented on common/scripted_effects/aroai_weekly_loop_effects.txt
need to confirm that subtract doesn't throw errors
I may be hallucinating that though I've got a wicked fever

2023-04-25 12:42 UTC, ademblon commented on common/production_methods/01_industry.txt
This is fixed

2023-04-25 13:28 UTC, JackEPepper approved these changes

2023-04-27 16:57 UTC, merged