Error log cleanup
Cold-War-Project/CWP-Main pull request #257
Opened 2023-04-25 16:30 UTC by raxo2222

Small error fixes

2023-04-25 18:46 UTC, JackEPepper approved these changes

2023-04-27 17:01 UTC, DZappala requested changes

2023-04-27 17:09 UTC, raxo2222 commented on common/cultures/00_cultures.txt
native_american_rights = {
	icon = gfx/interface/icons/timed_modifier_icons/modifier_statue_positive.dds
	state_cherokee_standard_of_living_add = 2
	state_muskogean_standard_of_living_add = 2
	state_algonquian_standard_of_living_add = 2
}
This one

2023-04-27 17:53 UTC, raxo2222 commented on common/cultures/00_cultures.txt
Now I have idea: I'll revert culture additions but add fake modifier types for them - it doesn't have to know, that cherokee is not state and muskogean is not building and is not something else

2023-04-27 19:04 UTC, closed without merging