feat: reworked spanish states + fixed its economy
Cold-War-Project/CWP-Main pull request #260
Opened 2023-04-26 17:43 UTC by Max200012

2023-04-27 17:05 UTC, JackEPepper requested changes
I'd like to see arable land in toledo upped to match the unemployed in the state, and to have urban center PMs active at game start.

2023-04-28 07:10 UTC, Max200012 commented
@JackEPepper balanced it out a bit more, they shouldn't have red SoL now

2023-04-28 15:10 UTC, JackEPepper approved these changes

2023-04-28 16:15 UTC, DZappala approved these changes

2023-04-28 16:15 UTC, merged