Fixed airports, but actually I didn't
Cold-War-Project/CWP-Main pull request #261
Opened 2023-04-27 15:18 UTC by DZappala

Importing all changes to the route networks sans any real fixes for airports. This is mostly just like models and shit.

2023-04-27 17:09 UTC, DZappala commented
⚠️ The Spain branch needs to be merged after this or else this will overwrite the Spain branch's splines.

2023-04-27 17:52 UTC, JackEPepper requested changes

2023-04-27 17:52 UTC, JackEPepper commented on common/scripted_triggers/00_scripted_triggers.txt
Overwrote superpower rival fix

2023-04-27 22:11 UTC, Arcadyi approved these changes

2023-04-28 15:14 UTC, JackEPepper approved these changes

2023-04-28 15:14 UTC, merged