Error log cleanup
Cold-War-Project/CWP-Main pull request #270
Opened 2023-04-30 11:00 UTC by raxo2222

Some more log error fixing

2023-05-01 21:19 UTC, JackEPepper approved these changes

2023-05-02 18:34 UTC, DZappala requested changes
Take a look at comment 😃

2023-05-02 18:34 UTC, DZappala commented on common/building_groups/00_building_groups.txt
Should slums have cash reserves?
Set to 0 (or 1 if 0 is not possible)

Or do buildings _need_ cash reserves in order for them to work? @JackEPepper @raxo2222

2023-05-02 18:34 UTC, DZappala commented on common/character_traits/cwp_traits.txt
Add the following line. 

```
#TODO create events and/or conditionals to allow lawyer characters to have some sway on passing laws [for 1.4 DLC release]
```

2023-05-02 19:12 UTC, raxo2222 commented on common/character_traits/cwp_traits.txt
Added

2023-05-02 19:22 UTC, raxo2222 commented on localization/english/triggers_l_english.yml
> + TRIGGER_FULLFILLMENT:0 "Fulfillment $COMPARATOR$ #variable $NUM$#!"
Interestingly its not used in \game\common\trigger_localization\00_trigger_localization.txt unlike others
I guess we can use correct spelling until we get a loc error

2023-05-03 17:16 UTC, DZappala commented on localization/english/triggers_l_english.yml
> + TRIGGER_FULLFILLMENT:0 "Fulfillment $COMPARATOR$ #variable $NUM$#!"
Haha oops Disappearance "-ance" is the correct spelling. Idk what I was smoking at the time.

2023-05-03 17:17 UTC, merged