State fixing
Cold-War-Project/CWP-Main pull request #275
Opened 2023-05-05 08:43 UTC by Max200012

- Removed Faroese culture; it was way too small and not relevant
- Merged Cayman Islands with Jamaica
- fixed misc ports, hubs, locators, naval exits, etc.
- fixed some province terrains in global islands and in korea

2023-05-05 15:20 UTC, JackEPepper approved these changes

2023-05-05 15:22 UTC, JackEPepper requested changes
Get error spam when I hover over the Cayman island province in Jamacia? 
![image](https://user-images.githubusercontent.com/100242026/236499984-99317901-8fda-456a-a5cb-cd2ea29431e8.png)

2023-05-05 15:30 UTC, JackEPepper approved these changes

2023-05-06 06:09 UTC, DZappala approved these changes

2023-05-06 06:09 UTC, merged