Error cleanup
Cold-War-Project/CWP-Main pull request #280
Opened 2023-05-07 11:42 UTC by raxo2222

2023-05-07 23:40 UTC, DZappala requested changes
Minor changes

2023-05-07 23:40 UTC, DZappala commented on localization/english/CWP/CWP_buildings_l_english.yml
> +  bg_telecommunications: "Telecommunications Industries"
syntax error: double plural.
```suggestion
  bg_telecommunications: "Telecommunication Industries"
```

2023-05-07 23:40 UTC, DZappala commented on localization/english/CWP/CWP_buildings_l_english.yml
> +  bg_tidal_power: "Todal Plants"
```suggestion
  bg_tidal_power: "Tidal Plants"
```
should be

2023-05-07 23:40 UTC, DZappala commented on localization/english/CWP/CWP_buildings_l_english.yml
> +  bg_civil_defense: "Civil Defense"
```suggestion
  bg_civil_defense: "Civil Defense Sectors"
```

2023-05-07 23:40 UTC, DZappala commented on localization/english/CWP/CWP_buildings_l_english.yml
> +  bg_foreign_service: "Foreign Service"
```suggestion
  bg_foreign_service: "Foreign Service Sectors"
```

2023-05-08 06:18 UTC, raxo2222 commented on localization/english/CWP/CWP_buildings_l_english.yml
> +  bg_telecommunications: "Telecommunications Industries"
fixed

2023-05-08 06:18 UTC, raxo2222 commented on localization/english/CWP/CWP_buildings_l_english.yml
> +  bg_tidal_power: "Todal Plants"
oops

2023-05-08 06:19 UTC, raxo2222 commented on localization/english/CWP/CWP_buildings_l_english.yml
> +  bg_civil_defense: "Civil Defense"
and done

2023-05-08 20:36 UTC, DZappala approved these changes

2023-05-09 20:23 UTC, JackEPepper approved these changes

2023-05-09 20:23 UTC, merged