Starting laws retouch
Cold-War-Project/CWP-Main pull request #402
Opened 2023-07-06 04:24 UTC by Mercur-3

Please Please Please

2023-07-06 18:20 UTC, JackEPepper requested changes
Need error fixing

2023-07-06 20:58 UTC, DZappala requested changes

2023-07-06 20:58 UTC, DZappala commented on common/history/countries/den - denmark.txt
> +			distributionOfPower = consensus_democracy
Most nations don't start with the tech for consensus democracy u less this requirement was changed

2023-07-06 20:58 UTC, DZappala commented on common/history/countries/abu - trucial states.txt
todo: needs refactoring

2023-07-06 20:58 UTC, DZappala commented on common/history/countries/ade - aden protectorate.txt
todo: needs refactoring

2023-07-06 20:58 UTC, DZappala commented on common/history/countries/afh - afganistan.txt
todo: needs refactoring

2023-07-06 20:58 UTC, DZappala commented on common/history/countries/alb - albania.txt
todo: needs refactoring

2023-07-06 20:58 UTC, DZappala commented on common/history/countries/arg - argentina.txt
todo: needs refactoring

2023-07-06 20:58 UTC, DZappala commented on common/history/countries/ast - australia.txt
removing a law from the effect will cause the entire effect to not work. This change needs to be undone.

2023-07-06 20:58 UTC, DZappala commented on common/history/countries/aus - austria.txt
> +			headOfGovernment = council_elective
soviet occupied austria should be 
administrative as it's a military occupation.

2023-07-06 20:58 UTC, DZappala commented on common/history/countries/azr - azerbaijan.txt
> +		activate_law = law_type:law_no_wmds
activate law can't be moved out of effect.

2023-07-06 20:58 UTC, DZappala commented on common/history/countries/bel - belgium.txt
> +		activate_law = law_type:law_regulated_human_trials
activate law can't be out of effect.

2023-07-06 20:58 UTC, DZappala commented on common/history/countries/bhn - bahrain.txt
> +		activate_law = law_type:law_regulated_human_trials
activate law can't be out of effect.

2023-07-06 20:58 UTC, DZappala commented on common/history/countries/bhu - bhutan.txt
Missing starting laws. all laws must be set. 
todo: needs refactoring

2023-07-06 20:58 UTC, DZappala commented on common/history/countries/bol - bolivia.txt
> +		activate_law = law_type:law_regulated_human_trials
activate law can't be added outside of effect.

2023-07-06 20:58 UTC, DZappala commented on common/history/countries/boz - british occupation zone.txt
> +		activate_law = law_type:law_professional_police
activate law can't be outside effect

2023-07-06 20:58 UTC, DZappala commented on common/history/countries/brd - Burundi.txt
> +		activate_law = law_type:law_professional_police
activate law can't be outside effect

2023-07-06 20:58 UTC, DZappala commented on common/history/countries/ddr - german democratic republic.txt
> +			distributionOfPower = anocracy
mil admins should be either autocracy or oligarchy.

2023-07-06 20:58 UTC, DZappala commented on common/history/countries/leb - lebanon.txt
> +			headOfGovernment = executive
Was this not a military occupation by the British at this time?

2023-07-06 20:58 UTC, DZappala commented on common/history/countries/nrk - north korea.txt
> +			distributionOfPower = anocracy
if this is occupied north Korea they should be administrative autocracy.

2023-07-06 20:58 UTC, DZappala commented on common/history/countries/stk - south korea.txt
> +			distributionOfPower = anocracy
mil admins should be autocracy or oligarchy.

2023-07-09 16:56 UTC, DZappala approved these changes

2023-07-09 18:37 UTC, JackEPepper approved these changes

2023-07-09 18:37 UTC, merged