fix: urbanists and laborists have opinions on economic system if decentralized
Cold-War-Project/CWP-Main pull request #501
Opened 2023-07-31 22:08 UTC by Mercur-3

nations that start with "decentralized" economic system now have 'social" urbanists and laborists

2023-07-31 22:53 UTC, JackEPepper requested changes

2023-07-31 22:53 UTC, JackEPepper commented on common/on_actions/00_code_on_actions.txt
> +								has_law = law_type:law_dec
```suggestion
								has_law = law_type:law_decentralization
```

2023-07-31 22:53 UTC, JackEPepper commented on common/on_actions/00_code_on_actions.txt
> +								has_law = law_type:law_dec
```suggestion
								has_law = law_type:law_decentralization
```

2023-07-31 22:54 UTC, JackEPepper commented
Need to change this branch to dev

2023-07-31 23:01 UTC, DZappala commented
> Need to change this branch to dev

done

2023-08-01 12:20 UTC, JackEPepper submitted a review, later dismissed

2023-08-01 22:44 UTC, DZappala requested changes

2023-08-01 22:44 UTC, DZappala commented on common/on_actions/00_code_on_actions.txt
>  							not = {
```suggestion
							nor = {
```

2023-08-01 22:44 UTC, DZappala commented on common/on_actions/00_code_on_actions.txt
>  							not = {
```suggestion
							nor= {
```

2023-08-01 22:44 UTC, DZappala commented on common/on_actions/00_code_on_actions.txt
> +							not = {
```suggestion
							nor = {
```

2023-08-01 22:44 UTC, DZappala commented on common/on_actions/00_code_on_actions.txt
>  							not = {
```suggestion
							nor = {
```

2023-08-01 22:44 UTC, DZappala commented on common/on_actions/00_code_on_actions.txt
>  							not = {
```suggestion
							nor = {
```

2023-08-01 22:44 UTC, DZappala commented on common/on_actions/00_code_on_actions.txt
> +							not = {
```suggestion
							nor = {
```

2023-08-01 22:45 UTC, DZappala approved these changes

2023-08-01 22:45 UTC, merged