Korean war
Cold-War-Project/CWP-Main pull request #502
Opened 2023-08-01 00:07 UTC by JackEPepper

- added intervention diplo action
- added korean reunification je
- added korean war je
- made korea a formable
- added mlk and oppenheimer agitators
- fixed wrong encoding on countries file
- adjusted starting tech levels, mostly downward
- nerfed command economy revenue back to vanilla levels

2023-08-01 02:24 UTC, Arcadyi approved these changes

2023-08-02 00:23 UTC, DZappala requested changes

2023-08-02 00:23 UTC, DZappala commented on localization/english/CWP/korea/korean_reunification_l_english.yml
> +korean_reunification.2.d: "Despite numerous attempts to bridge the gap and reunite the two Koreas, the negotiations for a reunification treaty ultimately collapsed due to insurmountable differences.
```suggestion
korean_reunification.2.d: "Negotiations on the reunification treaty collapsed due to contrasting economic systems and political ideologies, further exacerbated by influence from external powers."
```

2023-08-02 00:23 UTC, DZappala commented on localization/english/CWP/korea/korean_reunification_l_english.yml
> +korean_reunification.2.f: "As the diplomatic teams pack up and leave, some angry, others frustrated, and many saddened by the outcome of events, all know that this is not the end. Neither side is wil
```suggestion
korean_reunification.2.f: "As their diplomatic teams prepare to leave $EM_DASH$ some angry, others frustrated, and many saddened by the outcome $EM_DASH$ all know that this is not the end. Neither side is willing to back down. Whether they like it or not, the question of unification will be resolved not through diplomacy but through bloodshed."
```

2023-08-02 00:23 UTC, DZappala commented on localization/english/CWP/korea/korean_reunification_l_english.yml
> +korean_reunification.4.d: "An international mandate has been set for unifying Korea under a single government. Our nation is to take part in the negotiations." #Thanks Chatpt
```suggestion
korean_reunification.4.d: "The UN has passed a mandate to unify Korea under a single government. Our nation will participate in the negotiations."
```

2023-08-02 00:23 UTC, DZappala commented on localization/english/CWP/korea/korean_reunification_l_english.yml
> +korean_reunification.4.f: "As a homogeneous people, a great national unity shall be sought above all, transcending differences in ideas, ideologies, and systems. - July 4th North-South Joint Statemen
```suggestion
korean_reunification.4.f: "#italic As a unified people, we will transcend our differences in both ideology and economics. The only way forward is together.#! - July 4th North-South Joint Statement"
```

2023-08-02 00:23 UTC, DZappala commented on localization/english/names_l_english.yml
> +  Luther_king: "Luther King"
```suggestion
  Luther_king: "Luther King Jr."
```

2023-08-02 00:38 UTC, merged