Party-tweaks
Cold-War-Project/CWP-Main pull request #566
Opened 2023-08-14 20:45 UTC by DZappala

Changes:
- parties will now not try to join a party if there are no parties they want to join, rather than creating a new, small party
- party morale is capped at +- 10 reasons
- headliner ig scaled from 50 reasons to 5 reasons
- constricted parameters for which igs can join which parties, is now even more dependent on the joining IG's Law Stance.
- minor fixes to the "has voting franchise" scripted trigger
- added a ramp up in support for the green party the higher pollution gets.

Known Issues:
- the very first parties formed while the game is getting set up are still scuffed. They aren't accurate seemingly becuase the party join calculations happen procedurally. Since the party join calcs are dependent on how well a party is doing, some party numbers like morale, clout, cohesion, should be done before hand. 
  - one fix for the above would be to add some national modifiers that decay over time, a la HOI4. For instance, a "won WWII" modifier that boosts the IGs that were historically in government at the time the war was done. 
  - Another fix would be to really rigidly set the starting IGs which can be done somewhat deterministicly if someone is willing to put in the work. Special effects will need to be added to each party file that check for the year and the IG trying to join, and sets their resons to join a party to some arbitrarilly high number. 

- Leader IGs NEED to be set up in the near future for these mechanics to work as IG law stance determines which parties an IG can try to join.

- Laborists and Urbanists have extremely low levels of clout. Far lower than they should at this time across all nations.

2023-08-18 21:46 UTC, JackEPepper requested changes

2023-08-18 21:46 UTC, JackEPepper commented on common/on_actions/00_code_on_actions.txt
I'm concerned about the performance impact of adding a timed modifier to potentially thousands of characters every month.  Is this needed?

2023-08-19 00:10 UTC, DZappala commented on common/on_actions/00_code_on_actions.txt
This serves as a way to curb the same parties/igs winning elections over and over. The theory being is if you have an ig in government, it's leader's popularity will naturally tick down so that in 2-3 elections the IGs in power are more likely to shift around. 

Can you think of a bette ready to achieve the same effect?

2023-08-19 04:47 UTC, JackEPepper commented on common/on_actions/00_code_on_actions.txt
Is there a way to tie that into the outcome of an election?  Or perhaps now is the time to implement term limits.

2023-08-19 16:22 UTC, DZappala commented on common/on_actions/00_code_on_actions.txt
I think it's best to make it character based. Since we take into account popularity of leaders when deciding parties, there needs to be a way for that popularity to fluctuate like it does with irl office holders. I wouldn't mind a yearly tick down for a character, scaling the value up by 12 to match. Or, currently events based around character popularity really only fire during election season, we could create a slew of random events for popularity that play out during the election off season to achieve the same or a similar effect.

2023-08-20 01:26 UTC, JackEPepper commented on common/on_actions/00_code_on_actions.txt
I think the random events during off-seasons are the way to go.

I'll look into maybe tying it into corruption; on the coup branch I've worked out a way to give the AI a pseudo corruption value with basically zero performance impact so we can start integrating it into more systems (hopefully).

2023-08-27 17:52 UTC, merged